#!/usr/bin/expect
trap {
    send \x03
    send_user "You pressed Ctrl+C\n"
} SIGINT

set config [lindex $argv 0]
set passfile [lindex $argv 1]
set response [lindex $argv 2]
set timeout 120000
spawn openvpn --suppress-timestamps --nobind --config "$config" --auth-user-pass "$passfile"
expect "CHALLENGE: Enter Google Authenticator Code "
send -- "$response\r"
expect eof
